name: windows

# build on c/cpp changes or workflow changes
on:
  push:
    paths:
      - 'lib/**.[ch]'
      - 'lib/**.cpp'
      - 'src/**.[ch]'
      - 'src/**.cpp'
      - 'irr/**.[ch]'
      - 'irr/**.cpp'
      - '**/CMakeLists.txt'
      - 'cmake/Modules/**'
      - 'po/**.po'
      - 'util/buildbot/**'
      - 'misc/*'
      - '.github/workflows/windows.yml'
  pull_request:
    paths:
      - 'lib/**.[ch]'
      - 'lib/**.cpp'
      - 'src/**.[ch]'
      - 'src/**.cpp'
      - 'irr/**.[ch]'
      - 'irr/**.cpp'
      - '**/CMakeLists.txt'
      - 'cmake/Modules/**'
      - 'po/**.po'
      - 'util/buildbot/**'
      - 'misc/*'
      - '.github/workflows/windows.yml'

jobs:
  mingw:
    name: "MinGW cross-compiler (${{ matrix.config.bits }}-bit)"
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - { bits: 32, nsis: false }
          - { bits: 64, nsis: true }
    steps:
      - uses: actions/checkout@v7
      - name: Install compiler
        run: |
          source ./util/ci/common.sh
          install_mingw_deps '${{matrix.config.bits}}' '${{matrix.config.nsis}}'
          if '${{matrix.config.nsis}}'; then
            echo 'CMAKE_CXX_COMPILER_LAUNCHER=ccache' >>$GITHUB_ENV
          fi
          sudo ./util/buildbot/download_toolchain.sh /usr

      - name: Build
        run: |
           EXISTING_MINETEST_DIR=$PWD \
           ./util/buildbot/buildwin${{ matrix.config.bits }}.sh B
           mkdir -p artifact
           cp -v B/build/*.zip artifact/

      # Check that the resulting binary can run (DLLs etc.)
      - name: Runtime test
        run: |
          dest=$(mktemp -d)
          unzip -q -d "$dest" artifact/*.zip
          cd "$dest"/luanti-*-win*
          wine bin/luanti.exe --version

      - name: Build for NSIS
        run: |
           EXISTING_MINETEST_DIR=$PWD \
           ./util/buildbot/buildwin${{ matrix.config.bits }}.sh B -DRUN_IN_PLACE=0
           dest=$(mktemp -d)
           unzip -q -d "$dest" B/build/*.zip
           cd "$dest"/luanti-*-nsis
           makensis -WX -V3 sfx-launcher.nsi
           cp -v "$dest"/*.exe $GITHUB_WORKSPACE/artifact/
        if: ${{ matrix.config.nsis }}

      - uses: actions/upload-artifact@v7
        with:
          archive: false
          path: artifact/*.zip
          if-no-files-found: error

      - uses: actions/upload-artifact@v7
        with:
          archive: false
          path: artifact/*.exe
          if-no-files-found: error
        if: ${{ matrix.config.nsis }}

  msvc:
    name: VS 2026 ${{ matrix.config.arch }}
    runs-on: windows-2025-vs2026
    env:
      VCPKG_DEFAULT_TRIPLET: ${{matrix.config.vcpkg_triplet}}
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}\vcpkg_cache
      VCPKG_DISABLE_METRICS: 1
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              arch: x86,
              generator: "-G'Visual Studio 18 2026' -A Win32",
              vcpkg_triplet: x86-windows
            }
          - {
              arch: x64,
              generator: "-G'Visual Studio 18 2026' -A x64",
              vcpkg_triplet: x64-windows
            }

    steps:
      - uses: actions/checkout@v7

      - name: Setup vcpkg
        id: setup-vcpkg
        shell: pwsh
        run: |
          Remove-Item -Recurse -Force C:\vcpkg -ErrorAction Continue
          $baseline = (Get-Content -Raw vcpkg.json | ConvertFrom-Json).'builtin-baseline'
          Write-Host "builtin-baseline: $baseline"
          "VCPKG_BASELINE=$baseline" >> $env:GITHUB_OUTPUT
          New-Item -ItemType Directory -Force vcpkg_cache | Out-Null
          git clone --filter=blob:none --no-checkout https://github.com/microsoft/vcpkg.git vcpkg
          git -C vcpkg checkout $baseline
          .\vcpkg\bootstrap-vcpkg.bat
          Add-Content -Path "${{ github.workspace }}\vcpkg\triplets\${{ matrix.config.vcpkg_triplet }}.cmake" -Value "`nset(VCPKG_DISABLE_COMPILER_TRACKING ON)"

      - name: Restore vcpkg cache
        id: vcpkg-cache
        uses: actions/cache/restore@v6
        with:
          path: &vcpkg_cache_paths |
            ${{ github.workspace }}\vcpkg\downloads
            ${{ github.workspace }}\vcpkg_cache
          key: &vcpkg_cache_key ${{ runner.os }}-vcpkg-${{ matrix.config.vcpkg_triplet }}-${{ steps.setup-vcpkg.outputs.VCPKG_BASELINE }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-${{ matrix.config.vcpkg_triplet }}-${{ steps.setup-vcpkg.outputs.VCPKG_BASELINE }}-

      - name: CMake
        id: cmake
        run: |
          cmake ${{matrix.config.generator}}  `
          -DVCPKG_INSTALL_OPTIONS="--x-abi-tools-use-exact-versions"  `
          -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake"  `
          -DCMAKE_BUILD_TYPE=Release  `
          -DENABLE_POSTGRESQL=OFF  `
          -DENABLE_LUAJIT=TRUE  `
          -DREQUIRE_LUAJIT=TRUE  `
          -DRUN_IN_PLACE=1 .

      - name: Build
        run: cmake --build . --config Release

      - name: Unittests
        # need this workaround for stdout to work
        run: |
          $proc = start .\bin\Release\luanti.exe --run-unittests -NoNewWindow -Wait -PassThru
          exit $proc.ExitCode

      - name: CPack
        run: |
          cpack -G ZIP -B "$env:GITHUB_WORKSPACE\Package"
          rm -r $env:GITHUB_WORKSPACE\Package\_CPack_Packages
          Get-ChildItem "$env:GITHUB_WORKSPACE\Package\*.zip" | Rename-Item -NewName { $_.Name -replace '\.zip$', '-msvc.zip' }

      - name: Save vcpkg cache
        uses: actions/cache/save@v6
        if: always() && steps.cmake.outcome == 'success' && steps.vcpkg-cache.outputs.cache-hit != 'true'
        with:
          path: *vcpkg_cache_paths
          key: *vcpkg_cache_key

      - uses: actions/upload-artifact@v7
        with:
          archive: false
          path: .\Package\
          if-no-files-found: error
